### ISSUE TITLE
Wonderful library! But it seems abandoned?

### ISSUE THREAD

**Issue by justforcomment** [innoave/valid#9]
Wonderful library! But it seems abandoned?

I would like to thank the author, in my opinion, this tool can be a good alternative to other validation/parsing libraries (semval, garde, frunk).

Interested to know why there is no more activity? 

As a continuation of the previous issue, i would like to ask a similar question that i encountered when trying to implement the same logic: about flattening values passed to the and_then closure.

It's still more than usable.

Moreover, there are language limitations (lack of partial application, automatic carrying) that prevent an elegant solution to this problem.

Thank you, author! =)

**Comment by haraldmaida** [comment]
Thank you for the nice feedback.

I started this library as a side project to see if I can come up with an API I like and to code some more potentially useful things in Rust. If there are interessting feature requests maybe I will implement them. As you can see, so far there are no open issues (other than my own one regarding the flattening of arguments).
